### ISSUE TITLE
ragg crashes with some specific text

### ISSUE THREAD

**Issue by lepennec** [r-lib/ragg#77] opened 2021-03-08 14:47 UTC
Hi,

I've stumbled across a string that makes ragg crashes:
```
grid::grid.text("사랑")
```
yields a fatal error with ragg and not with the default engine (at least under fedora).
The text is supposed to correspond to "love" in korean but it may also be pure gibberish...

Let me know how I can help.

Erwan

**Comment by thomasp85** [comment] 2021-03-08 16:25
Hi

Thanks. I can't seem to reproduce this. Can I get you to ensure that you have the latest version of ragg and textshapinOSg?

If the issue persists I would like to get some info on your system

**Comment by lepennec** [comment] 2021-03-08 17:32
I've trie with the latest version on github and I observe the same issue.
I'm using Fedora Core 33 with the latest version of the CRAN package (as well as the latest package from github in the last experiment). 

I've tried outside Rstudio and this is the error I observe:
grid::grid.text("사랑")
/usr/include/c++/10/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = FontSettings; _Alloc = std::allocator<FontSettings>; std::vector<_Tp, _Alloc>::reference = FontSettings&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.

**Comment by lepennec** [comment] 2021-03-08 17:42
and here is the corresponding stack obtained with gdb:
```
gdb) bt
#0  0x00007fb9c715b9d5 in raise () from /lib64/libc.so.6
#1  0x00007fb9c71448a4 in abort () from /lib64/libc.so.6
#2  0x00007fb95353bfec in std::__replacement_assert(char const*, int, char const*, char const*) [clone .constprop.0] (__line=__line@entry=1045, 
    __function=__function@entry=0x7fb953540ae0 "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = FontSettings; _Alloc = std::allocator<FontSettings>; std::vector<_Tp, _Alloc>:"..., 
    __condition=__condition@entry=0x7fb953540058 "__builtin_expect(__n < this->size(), true)", __file=0x7fb953540878 "/usr/include/c++/10/bits/stl_vector.h")
    at /usr/include/c++/10/x86_64-redhat-linux/bits/c++config.h:2560
#3  0x00007fb95353d73d in std::vector<FontSettings, std::allocator<FontSettings> >::operator[] (this=<optimized out>, __n=<optimized out>)
    at /usr/include/c++/10/bits/stl_vector.h:1043
#4  std::vector<FontSettings, std::allocator<FontSettings> >::operator[] (
    this=<optimized out>, __n=2) at /usr/include/c++/10/bits/stl_vector.h:1043
#5  HarfBuzzShaper::shape_embedding (this=<optimized out>, 
    string=0x55875e560cf0, start=0, end=<optimized out>, string_length=2, 
    size=12, res=72, features=std::vector of length 0, capacity 0, emoji=false)
    at string_shape.cpp:655
#6  0x00007fb95353ec3f in HarfBuzzShaper::single_line_shape (
    this=0x55875e4c4010, string=<optimized out>, font_info=..., size=12, 
    res=72) at string_shape.cpp:399
--Type <RET> for more, q to quit, c to continue without paging--c
#7  0x00007fb953531e7a in ts_string_width (string=0x55875ee0e2f8 "사랑", font_info=..., size=12, res=72, include_bearing=1, width=0x7ffe42461fd8) at string_metrics.cpp:271
#8  0x00007fb952b3c916 in textshaping::string_width (res=72, width=0x7ffe42461fd8, include_bearing=1, size=12, font_info=..., string=0x55875ee0e2f8 "사랑") at /home/lepennec/R/x86_64-redhat-linux-gnu-library/4.0/textshaping/include/textshaping.h:34
#9  TextRenderer<agg::pixfmt_alpha_blend_rgba<agg::blender_rgba_pre<agg::rgba8T<agg::linear>, agg::order_rgba>, agg::row_accessor<unsigned char> > >::get_text_width (string=0x55875ee0e2f8 "사랑", this=0x55875e6d2ca8) at text_renderer.h:181
#10 AggDevice<agg::pixfmt_alpha_blend_rgba<agg::blender_rgba_pre<agg::rgba8T<agg::linear>, agg::order_rgba>, agg::row_accessor<unsigned char> >, agg::rgba8T<agg::linear>, agg::pixfmt_alpha_blend_rgba<agg::blender_rgba_pre<agg::rgba8T<agg::linear>, agg::order_rgba>, agg::row_accessor<unsigned char> > >::stringWidth (size=<optimized out>, face=<optimized out>, family=<optimized out>, str=0x55875ee0e2f8 "사랑", this=0x55875e6d2bd0) at AggDevice.h:266
#11 agg_strwidth<AggDeviceCapture<agg::pixfmt_alpha_blend_rgba<agg::blender_rgba_pre<agg::rgba8T<agg::linear>, agg::order_rgba>, agg::row_accessor<unsigned char> > > > (str=0x55875ee0e2f8 "사랑", gc=<optimized out>, dd=<optimized out>) at init_device.h:109
#12 0x00007fb9c7424a1c in GEStrWidth () from /usr/lib64/R/lib/libR.so
#13 0x00007fb9c7422018 in GEText () from /usr/lib64/R/lib/libR.so
#14 0x00007fb952e9cc82 in gridText () from /usr/lib64/R/library/grid/libs/grid.so
#15 0x00007fb952e9cd47 in L_text () from /usr/lib64/R/library/grid/libs/grid.so
#16 0x00007fb9c7412fa2 in R_doDotCall () from /usr/lib64/R/lib/libR.so
#17 0x00007fb9c7413aa5 in do_dotcall () from /usr/lib64/R/lib/libR.so
#18 0x00007fb9c7413e46 in do_dotcallgr () from /usr/lib64/R/lib/libR.so
#19 0x00007fb9c745e211 in bcEval.lto_priv.0 () from /usr/lib64/R/lib/libR.so
#20 0x00007fb9c743e7f8 in Rf_eval () from /usr/lib64/R/lib/libR.so
#21 0x00007fb9c743d5fe in R_execClosure () from /usr/lib64/R/lib/libR.so
#22 0x00007fb9c743e508 in Rf_applyClosure () from /usr/lib64/R/lib/libR.so
#23 0x00007fb9c745b44e in bcEval.lto_priv.0 () from /usr/lib64/R/lib/libR.so
#24 0x00007fb9c743e7f8 in Rf_eval () from /usr/lib64/R/lib/libR.so
#25 0x00007fb9c743d5fe in R_execClosure () from /usr/lib64/R/lib/libR.so
#26 0x00007fb9c743e508 in Rf_applyClosure () from /usr/lib64/R/lib/libR.so
#27 0x00007fb9c74ab085 in dispatchMethod.lto_priv.0 () from /usr/lib64/R/lib/libR.so
#28 0x00007fb9c7598f69 in Rf_usemethod.constprop.0 () from /usr/lib64/R/lib/libR.so
#29 0x00007fb9c74ab444 in do_usemethod () from /usr/lib64/R/lib/libR.so
#30 0x00007fb9c7452290 in bcEval.lto_priv.0 () from /usr/lib64/R/lib/libR.so
#31 0x00007fb9c743e7f8 in Rf_eval () from /usr/lib64/R/lib/libR.so
#32 0x00007fb9c743d5fe in R_execClosure () from /usr/lib64/R/lib/libR.so
#33 0x00007fb9c743e508 in Rf_applyClosure () from /usr/lib64/R/lib/libR.so
#34 0x00007fb9c745b44e in bcEval.lto_priv.0 () from /usr/lib64/R/lib/libR.so
#35 0x00007fb9c743e7f8 in Rf_eval () from /usr/lib64/R/lib/libR.so
#36 0x00007fb9c743d5fe in R_execClosure () from /usr/lib64/R/lib/libR.so
#37 0x00007fb9c743e508 in Rf_applyClosure () from /usr/lib64/R/lib/libR.so
#38 0x00007fb9c743ea12 in Rf_eval () from /usr/lib64/R/lib/libR.so
#39 0x00007fb9c7426128 in do_recordGraphics () from /usr/lib64/R/lib/libR.so
#40 0x00007fb9c74530e5 in bcEval.lto_priv.0 () from /usr/lib64/R/lib/libR.so
#41 0x00007fb9c743e7f8 in Rf_eval () from /usr/lib64/R/lib/libR.so
#42 0x00007fb9c743d5fe in R_execClosure () from /usr/lib64/R/lib/libR.so
#43 0x00007fb9c743e508 in Rf_applyClosure () from /usr/lib64/R/lib/libR.so
#44 0x00007fb9c745b44e in bcEval.lto_priv.0 () from /usr/lib64/R/lib/libR.so
#45 0x00007fb9c743e7f8 in Rf_eval () from /usr/lib64/R/lib/libR.so
#46 0x00007fb9c743d5fe in R_execClosure () from /usr/lib64/R/lib/libR.so
#47 0x00007fb9c743e508 in Rf_applyClosure () from /usr/lib64/R/lib/libR.so
#48 0x00007fb9c74ab085 in dispatchMethod.lto_priv.0 () from /usr/lib64/R/lib/libR.so
#49 0x00007fb9c7598e27 in Rf_usemethod.constprop.0 () from /usr/lib64/R/lib/libR.so
#50 0x00007fb9c74ab444 in do_usemethod () from /usr/lib64/R/lib/libR.so
#51 0x00007fb9c7452290 in bcEval.lto_priv.0 () from /usr/lib64/R/lib/libR.so
#52 0x00007fb9c743e7f8 in Rf_eval () from /usr/lib64/R/lib/libR.so
#53 0x00007fb9c743d5fe in R_execClosure () from /usr/lib64/R/lib/libR.so
#54 0x00007fb9c743e508 in Rf_applyClosure () from /usr/lib64/R/lib/libR.so
#55 0x00007fb9c745b44e in bcEval.lto_priv.0 () from /usr/lib64/R/lib/libR.so
#56 0x00007fb9c743e7f8 in Rf_eval () from /usr/lib64/R/lib/libR.so
#57 0x00007fb9c743d5fe in R_execClosure () from /usr/lib64/R/lib/libR.so
#58 0x00007fb9c743e508 in Rf_applyClosure () from /usr/lib64/R/lib/libR.so
#59 0x00007fb9c743ea12 in Rf_eval () from /usr/lib64/R/lib/libR.so
#60 0x00007fb9c7498f22 in Rf_ReplIteration () from /usr/lib64/R/lib/libR.so
#61 0x00007fb9c74992e0 in R_ReplConsole.lto_priv.0 () from /usr/lib64/R/lib/libR.so
#62 0x00007fb9c7499399 in run_Rmainloop () from /usr/lib64/R/lib/libR.so
#63 0x000055875b23f0af in main ()
```

**Comment by thomasp85** [comment] 2021-03-09 07:45
Thank you for the stack trace!

Is there anything special about your system or should I be able to replicate this in a Fedora 33 Core container?

**Comment by thomasp85** [comment] 2021-03-09 08:22
never mind - I've reproduced it in a container

thank you for reporting this

**Comment by thomasp85** [comment] 2021-03-09 13:07
This should now be fixed by installing the dev version of textahaping - can I get you to confirm?

Note that the issue appeared because the requested glyph was not found anywhere in your fonts (by font-config). If you are positive that you have a font that contains the glyph you should look into fixing your font-config configuration file (this is outside the scope of textshaping/systemfonts)

**Comment by lepennec** [comment] 2021-03-10 11:53
Indeed the issue is fixed! Thank you!

**Comment by thomasp85** [comment] 2021-03-10 11:57
Great - I'll send a patch release of textshaping to CRAN

**Closed by thomasp85** 2021-03-10 11:57 UTC
