### ISSUE TITLE
Some shapefile polygons do not get printed correctly using  geom_sf and ragg together

### ISSUE THREAD

**Issue by LaurentSmeets** [r-lib/ragg#62] opened 2020-11-02 07:50 UTC
I ran into [this](https://github.com/r-spatial/sf/issues/1522) issue of not correctly rendering alpha levels using a combination of `geom_sf` and `coord_sf` on Windows machines. I thought I had solved that problem using ragg. However, using ragg a new problem came up. When I use ragg as graphics engine a transformed polygon does not render as expected (in fill the whole plot and not just the 'inside' of the polygon.

### Using the default graphic engine

This is the expected output.

```
library(rworldmap)
library(sf)
library(tidyverse)
library(ragg)

polar_projection <- "+proj=stere +lat_0=90 +lat_ts=71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0"
World_map  <- getMap(resolution = "low")
World_map_transformed <- st_transform(st_as_sf(World_map),
                                      crs = polar_projection)

p1 <- ggplot() +
  geom_sf(data = World_map_transformed,
          fill = "#eddfb7",
          col = "black")+
  coord_sf( xlim = c(-4500000, 4500000),
            ylim = c(-4500000, 4500000), expand = F) 

ggsave("regular_graph.png", p1)
```
![image](https://user-images.githubusercontent.com/18034318/97842490-97808880-1cdf-11eb-96d1-14c19e4a47bf.png)

### Using the RAGG graphic engine

The polygon fill does not work

```
agg_png("agg_graph.png", width = 700, height = 700, res = 144)
p1
invisible(dev.off())
```
![image](https://user-images.githubusercontent.com/18034318/97842620-cdbe0800-1cdf-11eb-881b-77bf0fdc20d3.png)

**Comment by LaurentSmeets** [comment] 2020-11-02 08:02
Ok, it turns out that for me using `png(type="cairo")` solves both issues I had, still leaving this open as I would consider this unexpected behaviour.

**Comment by thomasp85** [comment] 2020-11-11 19:46
Thanks - I can reproduce

**Comment by thomasp85** [comment] 2020-11-11 19:59
Apparently Antarctica is the issue

**Comment by thomasp85** [comment] 2020-11-11 21:36
Digging deeper. This appears to be a bug deep inside the rasteriser of AGG. It is unlikely that this will ever get fixed unfortunately as AGG is no longer under active development.

Closing now because it cannot get fixed in ragg 😞

**Closed by thomasp85** 2020-11-11 21:36 UTC

**Comment by thomasp85** [comment] 2020-11-11 21:41
Just a last side-note. This is, incredibly enough, resolution dependent. The issue will only appear above a certain pixel size...

I wonder if it is a floating point issue somewhere

**Comment by LaurentSmeets** [comment] 2020-11-24 15:33
@thomasp85 , thanks for looking into this this thoroughly (bloody Antarctica). Anyways, for future readers, `cairo_png` does solve this problem
